랜딩페이지 기본작업 및 favicon 추가
Codeit-Sprint-Part-3-Team-8/Taskify pull request #22
Opened 2024-12-16 06:25 UTC by yunrap

## #️⃣ 연관된 이슈

- #18 

## 🔨작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

![스크린샷 2024-12-16 오후 12 21 48](https://github.com/user-attachments/assets/10cf28cb-a450-455f-8ce4-d1ff891d92df)

- [x] favicon, 메타정보추가
- [x] 랜딩페이지 기본 틀잡아보기

## 💬 리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

```
import mainImage from '@images/main.png';
```

app 폴더 안에서만 절대경로 사용이 가능하여 프로퍼티  tsconfig 추가하였습니다.

2024-12-16 11:02 UTC, Woolegend requested changes
NEXT.JS 환경에서 이미지의 포맷에 대해 알아보니 `.png`가 `.svg`보다 선호된다고 하네요!

해당 환경에서 `.png`는 렌더링 시 최적화 기능이 적용되지만 `.svg`는 오버라이드 하지않으면 최적화가 적용되지 않는다고 합니다

`.png`로 이미지 포맷을 선택하신건 좋은 선택인 거 같습니다

> https://hsp0418.tistory.com/210

랜딩페이지에 사용되는 이미지의 이름은 조금 더 명확하게 수정할 필요가 있어 보입니다.

main이나 part는 이미지의 역할을 나타내기엔 불분명한 거 같아요

![image](https://github.com/user-attachments/assets/349f5e33-6e39-424b-bd23-6a4bcf539c8c)

피그마에서는 landing과 resource를 사용해 이미지를 명시했는데 이 것을 따르는 것은 어떨까요?

- ex) `landing-resource-1.png`

꼭 제 추천을 따를 필요는 없지만 이름을 바꿀 필요는 있어 보이네요


이미지 경로를 바꿔야 하는 경우는 해당 페이지에 극한된 이슈가 아니다 보니 PR에만 이 사항을 남기기 보단 디스코드나 팀 회의에서 한 번 더 언급하시면 좋을 거 같습니다~

2024-12-16 11:02 UTC, Woolegend commented on tsconfig.json
> +      "@images/*": ["./public/images/*"]
항상 Image 컴포넌트에 이미지의 경로를 직접 넣어서 이런 오류가 있었는지 몰랐네요

2024-12-16 12:57 UTC, k-jipgeria requested changes

2024-12-16 12:57 UTC, k-jipgeria commented on app/page.tsx
> +          ></Image>
[ 태그 작성 방식 ]
Image tag처럼 content가 없는 경우 <Image />로 한 번에 작성할 수 있습니다!
특별한 이유가 없으시면 위 표기법이 좋은 것 같습니다!

2024-12-16 12:57 UTC, k-jipgeria commented on app/page.tsx
> +    </>
[ 빈 태그 작성 이유 ]
요소 전체를 감싸는 div tag가 있는 상황에서, 빈 태그를 사용하신 이유가 있으신가요?
합리적인 이유가 있으시면 수정 안 하셔도 됩니다!

2024-12-16 15:29 UTC, Donghunn-Lee approved these changes
확인이 너무 늦었네요. 앞서 남겨주신 `Image`의 셀프 클로징 태그 작성법 말고는 얘기할 게 없는 것 같습니다!

2024-12-16 16:13 UTC, bhoh032019 approved these changes
위에 다들 잘 말씀해주셔서 추가적으로 리뷰 할만한 사항은 없어 보이네요
고생하셨습니다

2024-12-17 01:16 UTC, yunrap commented
> NEXT.JS 환경에서 이미지의 포맷에 대해 알아보니 `.png`가 `.svg`보다 선호된다고 하네요!
> 
> 해당 환경에서 `.png`는 렌더링 시 최적화 기능이 적용되지만 `.svg`는 오버라이드 하지않으면 최적화가 적용되지 않는다고 합니다
> 
> `.png`로 이미지 포맷을 선택하신건 좋은 선택인 거 같습니다
> 
> > https://hsp0418.tistory.com/210
> 
> 랜딩페이지에 사용되는 이미지의 이름은 조금 더 명확하게 수정할 필요가 있어 보입니다.
> 
> main이나 part는 이미지의 역할을 나타내기엔 불분명한 거 같아요
> 
> ![image](https://private-user-images.githubusercontent.com/71242138/396067704-349f5e33-6e39-424b-bd23-6a4bcf539c8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzOTc4MTUsIm5iZiI6MTczNDM5NzUxNSwicGF0aCI6Ii83MTI0MjEzOC8zOTYwNjc3MDQtMzQ5ZjVlMzMtNmUzOS00MjRiLWJkMjMtNmE0YmNmNTM5YzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAxMDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMDljYzQ2NWJkZWIwOTYyYTYyNmY1YmQzNTc0ZDY3MmFlMjE4NzliNWZlODc1YTM4MmZiZDA4MGI3NmUyNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mRxBQChM7ea8Zv5nOwuDaoyyNglyrF8qwfU_fgpvYlo)
> 
> 피그마에서는 landing과 resource를 사용해 이미지를 명시했는데 이 것을 따르는 것은 어떨까요?
> 
> * ex) `landing-resource-1.png`
> 
> 꼭 제 추천을 따를 필요는 없지만 이름을 바꿀 필요는 있어 보이네요
> 
> 이미지 경로를 바꿔야 하는 경우는 해당 페이지에 국한된 이슈가 아니다 보니 PR에만 이 사항을 남기기 보단 디스코드나 팀 회의에서 **한 번 더 언급**하시면 좋을 거 같습니다~

네!~ 이미지경로 부분 회의때 얘기해보겠습니다!~
이미지 파일이름은 다음pr때 반영해서 수정하겠습니다 
자세한 pr 👍

2024-12-17 01:18 UTC, yunrap commented on app/page.tsx
> +    </>
네!~ 수정하니 소스코드가 확짧아지네요 ㅎㅎㅎ 반영할게요

2024-12-17 06:14 UTC, Woolegend approved these changes
고생하셨습니다~

2024-12-17 07:12 UTC, k-jipgeria approved these changes

2024-12-17 07:55 UTC, merged