[Feat] 사이드바 api 연결
Codeit-Sprint-Part-3-Team-8/Taskify pull request #31
Opened 2024-12-16 16:06 UTC by bhoh032019

## #️⃣ 연관된 이슈

- #23 

## 🔨작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

- [x] axios를 이용한 api 연결
- [x]  response에 존재하는 데이터 화면에 출력
  - 참여중인 대시보드가 존재할 경우 대시보드 데이터를 화면에 출력
  - 참여중인 대시보드가 존재하지 않을 경우 빈 화면 출력 
- [x]  내가 생성한 대시보드의 경우 추가 이미지 출력

## 💬 리뷰 요구사항(선택)

- 로그인 기능이 아직 구현되지 않았기 때문에 accessToken의 경우 swagger를 이용해 accessToken을 발급받아 직접 헤더에 추가해 api를 연결했습니다.
- 디자인은 고려하지 않았습니다.
- 동일한 api 함수가 여러 페이지에서 사용될 경우를 고려하지 않고 우선 연결을 통한 기능 구현을 목적으로 하나의 파일에 함수를 작성했습니다. 여러 페이지에서 해당 api함수가 필요한 경우 리팩토링을 통해 수정하겠습니다.

2024-12-16 16:12 UTC, Woolegend requested changes
`dev` 브랜치의 변경 사랑이 `feat/12--sidebar` 브랜치에 적용이 되지 않았습니다.

해당 브랜치에서의 변경사항만 파악하기 어렵습니다.

dev 브랜치의 변경사항을 해당 브랜치의 상위 브랜치에 먼저 적용 부탁드립니다.

2024-12-16 17:15 UTC, bhoh032019 commented
넵 `dev` 브랜치의 변경사항을 상위 브랜치에 적용했습니다

2024-12-16 17:20 UTC, Woolegend approved these changes
제가 볼 땐 문제 없어 보입니다! 고생하셨습니다~

2024-12-17 02:09 UTC, yunrap approved these changes
승인드립니다! 👍

2024-12-17 02:09 UTC, yunrap commented on app/_components/sidebar/SideBar.tsx
> +  }
와우!! api 첫스타트 당첨이십니다!! ㅎㅎ
api 파일을 분리해서 만들면 더 통일되서 좋을거같습니다

2024-12-17 03:15 UTC, Donghunn-Lee approved these changes
확인했습니다~! 변경사항 있다면 알려주시고 아니면 이대로 머지하셔도 될 것 같아요.

2024-12-17 03:15 UTC, Donghunn-Lee commented on app/_components/sidebar/SideBar.tsx
>      </div>
삼항 연산자는 가급적 줄이는 게 좋습니다. 중첩되는 경우는 특히 더 그렇습니다.

```js
<div>
  {myDashBoards.length > 0 &&
    myDashBoards.map((dashboard) => (
      <div key={dashboard.id}>
        <div
          className="h-2 w-2 rounded-full"
          style={{ backgroundColor: dashboard.color }}
        ></div>
        {dashboard.title}
        {dashboard.createdByMe && (
          <Image
            width={17.59}
            height={14}
            src="/ic-crown.svg"
            alt="CrownIcon"
          />
        )}
      </div>
    ))}
  {myDashBoards.length === 0 && <div></div>}
</div>
```

예를 들면 이런 식으로 데이터가 없는 경우를 분리해서 처리할 수 있을 것 같습니다.

2024-12-17 04:30 UTC, bhoh032019 commented on app/_components/sidebar/SideBar.tsx
>      </div>
넵! 확인했습니다. 가독성을 고려해 말씀해주신 방법으로 코드를 수정해보도록 하겠습니다.
감사합니다!!

2024-12-17 06:29 UTC, merged