폰트전역 추가
Codeit-Sprint-Part-3-Team-8/Taskify pull request #57
Opened 2024-12-19 06:24 UTC by yunrap

## #️⃣ 연관된 이슈

- #53 

## 🔨작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

- [x] 폰트전역 추가 작업

## 💬 리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

[지식공유]
woff2 확장자를 사용하였습니다. 기본 woff: 대부분의 모던브라우저에서 지원해주는 것보다 압축률이 30% 더좋다고합니다!~

Next.js의 next/font를 사용하는 경우에는 font를 빌드 타임 때 한번만 다운로드 받고, 
fallback font가 사용되는 동안 css size-adjust 프로퍼티를 적용시켜서 글자 크기를 동일하게하여 
layout shift 가 발생하는 것을 막아준다고하네요!~

참고 url 공유드려요!~
https://dev.to/algoorgoal/nextjs-tailwindcsse-pretendard-ponteu-jeogyonghagi-1g87

2024-12-19 07:38 UTC, Donghunn-Lee approved these changes

2024-12-19 10:48 UTC, Woolegend approved these changes
이런 방법이 있었군요!

확인했습니다~

2024-12-19 10:49 UTC, bhoh032019 approved these changes
감사합니다!!

2024-12-19 16:42 UTC, Woolegend requested changes
코드에서 충돌이 발생했습니다. 우선 해당 작업을한 브랜치에 origin/dev를 병합하신 후, 로컬에서 충돌을 해결하고 push 부탁드립니다.

2024-12-20 03:57 UTC, Woolegend approved these changes

2024-12-20 04:31 UTC, merged